import pandas as pd
import requests
from sklearn.ensemble import RandomForestRegressor
from datetime import datetime

# MVP Weather Prediction Model for KMIA
# Note: For production-level accuracy, replace 'get_forecast()' 
# with a function that reads historical CSV files from a site like 
# Iowa State Mesonet (ASOS/AWOS archive).

class WeatherModel:
    def __init__(self):
        self.model = RandomForestRegressor(n_estimators=100)
        self.lat, self.lon = 25.7959, -80.2870
        self.headers = {"User-Agent": "WeatherModelMVP/1.0 (contact@example.com)", "Accept": "application/geo+json"}

    def get_data(self):
        # Reads historical data from local CSV (kmia_extended.csv)
        # generated by data_collector.py
        df = pd.read_csv('kmia_extended.csv')
        for col in ['tmpf', 'dwpf', 'sknt', 'drct']:
            df[col] = pd.to_numeric(df[col], errors='coerce')
        df = df.dropna()
        df['valid'] = pd.to_datetime(df['valid'])

        # Aggregate to daily highs
        daily = df.groupby(df['valid'].dt.date).agg({
            'tmpf': 'max',
            'dwpf': 'mean',
            'sknt': 'mean',
            'drct': 'mean'
        }).reset_index()
        daily.columns = ['date', 'max_temp', 'mean_dewpoint', 'mean_wind_speed', 'mean_wind_dir']
        daily['date'] = pd.to_datetime(daily['date'])
        return daily

    def train(self):
        df = self.get_data()
        df['day_of_year'] = pd.to_datetime(df['time']).dt.dayofyear
        X = df[['day_of_year', 'pop']]
        y = df['temp']
        self.model.fit(X, y)
        return "Model trained on sample set."

    def predict(self, pop):
        day = datetime.now().timetuple().tm_yday
        return self.model.predict([[day, pop]])[0]

if __name__ == "__main__":
    wm = WeatherModel()
    print(wm.train())
    print(f"Predicted high with 50% pop: {wm.predict(50):.1f} F")
